apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgf.ci.cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NateAI/pgf.ci.cd.from.scratch.app.config.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd