apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgf-app-deployment
  labels:
    app: pgf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgf-app
  template:
    metadata:
      annotations:
        argocd-image-updater.argoproj.io/image-list: <image_alias>=742196880003.dkr.ecr.eu-west-1.amazonaws.com/pgf:latest
      labels:
        app: pgf-app
    spec:
      containers:
        - name: pgf-app
          image: 742196880003.dkr.ecr.eu-west-1.amazonaws.com/pgf:8b492611a03d8cf89c747e5dc40e2a2e3eba550c
          ports:
            - containerPort: 3000
