apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgf-app-deployment
  labels:
    app: pgf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgf-app
  template:
    metadata:
      annotations:
        argocd-image-updater.argoproj.io/image-list: <image_alias>=673278370432.dkr.ecr.eu-west-1.amazonaws.com/pgf:latest
      labels:
        app: pgf-app
    spec:
      containers:
        - name: pgf-app
          image: 673278370432.dkr.ecr.eu-west-1.amazonaws.com/pgf:latest
          ports:
            - containerPort: 3000
