apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- name: 673278370432.dkr.ecr.eu-west-1.amazonaws.com/pgf
  newName: 673278370432.dkr.ecr.eu-west-1.amazonaws.com/pgf
  newTag: f57c816fac56ca4313cddd89fb0655251f05126c
