apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- externalsecret.yaml
- secretstore.yaml
images:
- name: 673278370432.dkr.ecr.eu-west-1.amazonaws.com/pgf
  newName: 673278370432.dkr.ecr.eu-west-1.amazonaws.com/pgf
  newTag: 9fa7858599c85c120ef7e64c1104319ce4c52b55
